In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Sim
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [16]:
sales = pd.read_csv('spots_sales.csv')
X = sales.No_of_spots
y = sales.Sales

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [24]:
sales.head()

No_of_spots  Sales
0            8     25
1           12     34
2           16     39
3           10     32
4            8     22

In [25]:
model= LinearRegression()

In [26]:
lin_reg = model.fit(X_train, y_train)

ValueError: Expected 2D array, got 1D array instead:
array=[12 10 10  8 12  8].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [13]:
print("the intercept of the model {}". format(lin_reg.intercept_))
print("the coefficient of the model {}". format(lin_reg.coef_))
print('print the R squared score of the model {:.3f}'.format(lin_reg.score(X, y)))


the intercept of the model [25. 34. 39. 32. 22. 30. 43. 31.]
the coefficient of the model [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
print the R squared score of the model 1.000
